import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FAF9F9",
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 10,
    // Clear bottom space so the Emergency Card rests neatly above the tab bar
    paddingBottom: 20,
    alignItems: "center",
  },
  headerContainer: {
    width: "100%",
    maxWidth: 380,
    marginBottom: 8,
  },
  greetingTitle: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#D88DBA",
  },
  subTitle: {
    fontSize: 13,
    color: "#4A4A4A",
    marginTop: 2,
  },
  mapContainer: {
    width: "100%",
    maxWidth: 380,
    // Restored to 430px height to fill out screen height perfectly
    height: 430,
    borderRadius: 22,
    overflow: "hidden",
    position: "relative",
    marginVertical: 10,
    alignSelf: "center",
    backgroundColor: "#F5F5F5",
  },
  mapImage: {
    width: "100%",
    height: "100%",
    borderRadius: 22,
  },
  locationPill: {
    position: "absolute",
    bottom: 18,
    left: 16,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 20,
    elevation: 3,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
  },
  locationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#D88DBA",
    marginRight: 8,
  },
  locationText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#333333",
  },
  emergencyCard: {
    width: "100%",
    maxWidth: 380,
    backgroundColor: "#FFF0F4",
    borderRadius: 20,
    padding: 14,
    marginTop: 4,
    borderWidth: 1,
    borderColor: "#FEE5EC",
    alignSelf: "center",
  },
  emergencyHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  sirenBadge: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#D9383A",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  sirenIcon: {
    width: 20,
    height: 20,
    tintColor: "#FFFFFF",
  },
  emergencyTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#600000",
  },
  emergencyActionsContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 6,
  },
  contactButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  blueCircle: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#3B72EC",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
  },
  redCircle: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#E03131",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
  },
  hotlineText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "bold",
  },
  buttonLabel: {
    fontSize: 10,
    fontWeight: "500",
    color: "#555555",
    textAlign: "center",
    lineHeight: 13,
  },
  divider: {
    width: 1,
    height: 46,
    backgroundColor: "#F0F0F0",
    alignSelf: "center",
  },
});
